const data = {
    "drinks": [
        {
            "idDrink": "13501",
            "strDrink": "ABC",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Shot",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Shot glass",
            "strInstructions": "Layered in a shot glass.",
            "strInstructionsES": "Coloque todos los ingredientes en un vaso de chupito.",
            "strInstructionsDE": "Schichtaufbau in einem Schnapsglas.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
            "strIngredient1": "Amaretto",
            "strIngredient2": "Baileys irish cream",
            "strIngredient3": "Cognac",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1/3 ",
            "strMeasure2": "1/3 ",
            "strMeasure3": "1/3 ",
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2016-08-31 19:32:08"
        },
        {
            "idDrink": "17239",
            "strDrink": "Hunter's Moon",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Balloon Glass",
            "strInstructions": "Put the Bombay Sapphire, Martini Bianco, sugar syrup & blackberries in a cocktail shaker with lots of ice and shake vigorously before pouring into a balloon glass, topping up with lemonade and garnishing with a wedge of orange.",
            "strInstructionsES": null,
            "strInstructionsDE": "Den Bombay Saphir, Martini Bianco, Zuckersirup & Brombeeren in einen Cocktailshaker mit viel Eis geben und kräftig schütteln, bevor man sie in ein Ballonglas gießt, mit Limonade auffüllt und mit einem Stück Orange garniert.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Mettere il Bombay Sapphire, il Martini Bianco, lo sciroppo di zucchero e le more in uno shaker con molto ghiaccio e agitare energicamente prima di versare in un bicchiere a palloncino, rabboccare con limonata e guarnire con uno spicchio di arancia.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/t0iugg1509556712.jpg",
            "strIngredient1": "Vermouth",
            "strIngredient2": "Maraschino Cherry",
            "strIngredient3": "Sugar Syrup",
            "strIngredient4": "Lemonade",
            "strIngredient5": "Blackberries",
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "25 ml",
            "strMeasure2": "15 ml",
            "strMeasure3": "10 ml",
            "strMeasure4": "100 ml",
            "strMeasure5": "2",
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-11-01 17:18:32"
        },
        {
            "idDrink": "12089",
            "strDrink": "Rum Old-fashioned",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Ordinary Drink",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Old-fashioned glass",
            "strInstructions": "Stir powdered sugar, water, and bitters in an old-fashioned glass. When sugar has dissolved add ice cubes and light rum. Add the twist of lime peel, float 151 proof rum on top, and serve.",
            "strInstructionsES": null,
            "strInstructionsDE": "Puderzucker, Wasser und Bitter in einem old-fashioned Glas verrühren. Wenn sich der Zucker aufgelöst hat, Eiswürfel und leichten Rum hinzufügen. Die Limettenspirale hinzufügen, 151er Rum darauf verteilen und servieren.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Mescolare lo zucchero, l'acqua e il bitter in un bicchiere vecchio stile. Quando lo zucchero si sarà sciolto aggiungere i cubetti di ghiaccio e il rum chiaro. Aggiungere la scorza di lime, far galleggiare sopra 151 rum e servire.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/otn2011504820649.jpg",
            "strIngredient1": "Light rum",
            "strIngredient2": "151 proof rum",
            "strIngredient3": "Powdered sugar",
            "strIngredient4": "Bitters",
            "strIngredient5": "Water",
            "strIngredient6": "Lime peel",
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 1/2 oz ",
            "strMeasure2": "1 tsp ",
            "strMeasure3": "1/2 tsp ",
            "strMeasure4": "1 dash ",
            "strMeasure5": "1 tsp ",
            "strMeasure6": "Twist of ",
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-09-07 22:44:09"
        },
        {
            "idDrink": "16047",
            "strDrink": "Campari Beer",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Beer",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Beer mug",
            "strInstructions": "Use a 15 oz glass. Add Campari first. Fill with beer.",
            "strInstructionsES": null,
            "strInstructionsDE": "Verwenden Sie ein 15 oz Glas. Zuerst Campari hinzufügen. Mit Bier auffüllen.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Usa un bicchiere da 450ml.\r\nAggiungi prima Campari.\r\nRiempi di birra.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xsqrup1441249130.jpg",
            "strIngredient1": "Lager",
            "strIngredient2": "Campari",
            "strIngredient3": null,
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 bottle ",
            "strMeasure2": "1 1/2 cl ",
            "strMeasure3": null,
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2015-09-03 03:58:50"
        },
        {
            "idDrink": "17141",
            "strDrink": "Smut",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Punch / Party Drink",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Beer mug",
            "strInstructions": "Throw it all together and serve real cold.",
            "strInstructionsES": null,
            "strInstructionsDE": "Schütte alles zusammen und serviere es kalt.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Metti tutto insieme e servi freddo.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg",
            "strIngredient1": "Red wine",
            "strIngredient2": "Peach schnapps",
            "strIngredient3": "Pepsi Cola",
            "strIngredient4": "Orange juice",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1/3 part ",
            "strMeasure2": "1 shot ",
            "strMeasure3": "1/3 part ",
            "strMeasure4": "1/3 part ",
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-09-02 16:23:32"
        },
        {
            "idDrink": "13086",
            "strDrink": "Atomic Lokade",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Ordinary Drink",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Collins Glass",
            "strInstructions": "In a shaker, place lemonade, vodka, blue Curacao, and triple sec together. Shake with ice and strain into glass. Add sugar to taste",
            "strInstructionsES": "En una coctelera, combine la limonada, el vodka, el Blue Curaçao y el triple seco. Agitar con hielo y colar en un vaso. Añadir azúcar al gusto.",
            "strInstructionsDE": "In einem Shaker Limonade, Wodka, blauen Curacao und Triple Sec vermengen. Mit Eis schütteln und in ein Glas abseihen. Nach Belieben Zucker hinzufügen",
            "strInstructionsFR": null,
            "strInstructionsIT": "In uno shaker, mettere insieme la limonata, la vodka, il blue Curacao e il triple sec.\r\nShakerare con ghiaccio e filtrare nel bicchiere.\r\nAggiungere lo zucchero a piacere",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/n3zfrh1493067412.jpg",
            "strIngredient1": "Lemonade",
            "strIngredient2": "Vodka",
            "strIngredient3": "Blue Curacao",
            "strIngredient4": "Triple sec",
            "strIngredient5": "Sugar",
            "strIngredient6": "Ice",
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "5 oz ",
            "strMeasure2": "1 oz ",
            "strMeasure3": "1/2 oz ",
            "strMeasure4": "1/2 oz ",
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-04-24 21:56:52"
        },
        {
            "idDrink": "11029",
            "strDrink": "Amaretto Tea",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Ordinary Drink",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Pousse cafe glass",
            "strInstructions": "Pour hot tea into a pousse-cafe glass, using a spoon in glass to prevent cracking. Add amaretto, but do not stir. Top with chilled whipped cream and serve.",
            "strInstructionsES": "Vierta el té caliente en una taza pousse-café, usando una cuchara en la taza para evitar que se agriete. Agregue el Amaretto, pero no revuelva. Cubra con crema batida fría y sirva.",
            "strInstructionsDE": "Gießen Sie heißen Tee in ein Pousse-Café Glas und verwenden Sie einen Löffel im Glas, um Sprünge zu vermeiden. Amaretto hinzufügen, aber nicht rühren. Mit gekühlter Schlagsahne garnieren und servieren.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Versare il tè caldo in un bicchiere pousse-cafe, usando un cucchiaio in vetro per evitare che si spezzi. Coprire con panna montata fredda e servire.Aggiungere l'amaretto, ma non mescolare",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/b7qzo21493070167.jpg",
            "strIngredient1": "Tea",
            "strIngredient2": "Amaretto",
            "strIngredient3": "Whipped cream",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "6 oz hot ",
            "strMeasure2": "2 oz ",
            "strMeasure3": "Chilled ",
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-04-24 22:42:47"
        },
        {
            "idDrink": "12672",
            "strDrink": "Fruit Flip-Flop",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Other/Unknown",
            "strIBA": null,
            "strAlcoholic": "Non alcoholic",
            "strGlass": "Highball Glass",
            "strInstructions": "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.",
            "strInstructionsES": null,
            "strInstructionsDE": "Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/nfdx6p1484430633.jpg",
            "strIngredient1": "Yoghurt",
            "strIngredient2": "Fruit juice",
            "strIngredient3": null,
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 cup ",
            "strMeasure2": "1 cup ",
            "strMeasure3": null,
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-01-14 21:50:33"
        },
        {
            "idDrink": "16311",
            "strDrink": "Applejack",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Cocktail glass",
            "strInstructions": "Add all ingredients into mixing glass, chill and strain into cocktail glass",
            "strInstructionsES": "Añadir todos los ingredientes en un vaso mezclador, enfriar y colar en un vaso de cóctel.",
            "strInstructionsDE": "Alle Zutaten in das Mischglas geben, kühlen und in das Cocktailglas abseihen.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Aggiungere tutti gli ingredienti nel mixing glass, raffreddare e filtrare in una coppetta da cocktail",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/sutyqp1479209062.jpg",
            "strIngredient1": "Jack Daniels",
            "strIngredient2": "Midori melon liqueur",
            "strIngredient3": "Sour mix",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 oz ",
            "strMeasure2": "1/2 oz ",
            "strMeasure3": "2 oz ",
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2016-11-15 11:24:22"
        },
        {
            "idDrink": "12712",
            "strDrink": "Grape lemon pineapple Smoothie",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Other/Unknown",
            "strIBA": null,
            "strAlcoholic": "Non alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Throw everything into a blender and liquify.",
            "strInstructionsES": null,
            "strInstructionsDE": "Alles in einen Mixer geben und aufschlagen.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Getta tutto in un frullatore e liquida.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/54z5h71487603583.jpg",
            "strIngredient1": "Grapes",
            "strIngredient2": "Lemon",
            "strIngredient3": "Pineapple",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 cup ",
            "strMeasure2": "1/4 ",
            "strMeasure3": "1/2 ",
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2017-02-20 15:13:03"
        }
    ]
}
export default data;
